#!/bin/bash

# Copies a file owned by you to the same file path location on one or more
# remote hosts, retaining its timestamps and rwx props on the remote hosts.

if [ ! -f "$1" ] || [ ! -r "$1" ]
then
    echo -e "\n'$1': Arg 1 is a path to a readable file."
    exit 1
fi
file="$1"

shift 1
if [ -z "$1" ]
then
    echo -e "\nArgs 2+ are nicknames of ssh hosts to copy arg 1 to."
    exit 1
fi

for h in $@
do
    echo -e "\n$ scp -p $file $h:$file"
    scp -p -o IdentitiesOnly=true "$file" "$h:$file"
done

