#!/bin/bash

# Copyright (C) 2020 drpawpaw. All Rights Reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Tails journald files or syslog using common journalctl, tail and grep params.


sl=false
n=1000

declare -i shft=0
while getopts ":sn:" param
do
    case $param in

        s  ) declare -r sl=true ;
             shft=1+shft ;;

        n  ) declare -r n=$OPTARG ;
             shft=2+shft ;;

        \? ) echo -e "\nUsage: $ ${0##*/} [-s] [-n {postive int}]" ;
             exit ;;
    esac
done
(( 0 < $shft )) && shift $shft


if [ -n "$1" ]
then
    colr=--color
    grp="$1"
else
    colr=""
    grp='.*'
fi


echo -e "\n$ sudo journalctl --disk-usage"
sudo journalctl --disk-usage


if $sl
then
    echo -e \
         "\n$ sudo tail -n $n -F /var/log/syslog  | grep -iE $colr \"$grp\""

    sudo tail -n $n -F /var/log/syslog  | grep -iE $colr "$grp"

else
    echo -e "\n$ sudo journalctl -a -n 1000 -f -o short-precise --no-pager |" \
                     "grep -iE $colr \"$grp\""

    sudo journalctl -a -n $n -f -o short-precise --no-pager | \
         grep -iE $colr "$grp"
fi

