#!/bin/bash

# Starts a GUI on a remote host that displays in local host's X Windows.
# Assumes user's local host .ssh/config contains an entry for the remote
# host that defines a nickname.

# For remote apps that need space-containing args,
# backslash escape single and double-quotes once:
#
#   $ remote-gui-start {remote host} {remote-app} \"arg 1\" \'arg 2\' arg3...
#

conType=-X
if [ '-Y' = "$1" ]
then
    conType=$1
    shift 1
fi

if [ -z "$1" ] || [ -z "$2" ]
then
    echo -e "\nUsage: $ ${0##*/} {remote-ssh-host-nickame}" \
                                "{gui app to start} [app's args]"
    exit 1
fi

remote=$1
shift 1
simple=$( echo "${1##*/}" | sed -r "s/ .*//" )
out="$HOME"/.x-$remote-$simple.out

# -f tells ssh to move into background after prompting for password, which
# enables hidden password echo, whereas & causes clear-text password echo.
echo
echo "$ ssh -vf $conType $remote -- $@ &>\"$out\""
ssh -vf $conType $remote -- $@ &>"$out"

touch "$out"
chmod go-rwx "$out"
echo -e "\nstdout/err -> $out"

