#!/bin/bash

# Copyright (C) 2018,2020 drpawpaw. All Rights Reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Runs a passed in command (line) under a randomly named temporary user.
#
# Deletes the temp user after the passed in command exits.
#
# Passed in command's start dir is temp user's home dir.
#
# Files created in the temp user's home dir that should be retained after this
# script exits need to be copied or moved from the temp home dir before exiting
# the passed in command.


if [ "0" != "$(id -u)" ] || [ -z "$SUDO_USER" ]
then
    echo
    echo "${0##*/} only runs as sudo root."
    exit 1
fi

if [ -z "$1" ]
then
    echo -e "\n${0##*/}: No command passed in to run as temp user.\n" >&2
    exit 1
fi


# Lists of names are easy to find on the web. One name per line.
declare -r FIRST_NAMES_FILE="/home/$SUDO_USER/bin/config/names-english-first.txt"
declare -r LAST_NAMES_FILE="/home/$SUDO_USER/bin/config/names-english-last.txt"

if [ ! -f "$FIRST_NAMES_FILE" ] || [ ! -r "$FIRST_NAMES_FILE" ]
then
    echo -e "\nCan't read $FIRST_NAMES_FILE.\n" >&2
    exit 1
fi

if [ ! -f "$LAST_NAMES_FILE" ] || [ ! -r "$LAST_NAMES_FILE" ]
then
    echo -e "\nCan't read $LAST_NAMES_FILE.\n" >&2
    exit 1
fi


declare -i i=0
while (( 10 > i ))
do
    i=i+1
    u=$( shuf -n 1 "$FIRST_NAMES_FILE" |
         sed -r 's/^  *//' |
         cut -d ' ' -f1 |
         tr '[:upper:]' '[:lower:]' )
     ( ! id $u &>/dev/null ) && break
done

if id $u &>/dev/null
then
    echo -e "\nFailed to establish a temp username.\n" >&2
fi

declare -r firstName=$( sed -r 's/(.)/\u\1/' <<< $u )
declare -r userName=$u


declare -r lastName=$( shuf -n 1 "$LAST_NAMES_FILE" |
                       sed -r 's/^  *//' |
                       cut -d ' ' -f1 )
if [ -z "$lastName" ]
then
    echo -e "\nFailed to set last name.\n" >&2
    exit 1
fi

declare -r homeDir=/home/$userName


echo >&2
set -o xtrace
useradd --comment "$firstName $lastName" \
        --no-user-group \
        --no-log-init \
        --home-dir $homeDir \
        --create-home \
        $userName
set +o xtrace

if ! grep -E "^$userName:" /etc/passwd &>/dev/null
then
    echo -e "\nFailed to create tmp user ${userName}.\n" >&2
    exit 1
fi

sudo --login -u $userName "$@"

echo >&2
set -o xtrace
userdel --remove $userName 2>/dev/null
set +o xtrace

