#!/bin/bash

# Copyright (C) 2013,2020 drpawpaw. All Rights Reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Transforms aspell's default output to a nicer cmd line format.


if [ -z "$1" ] || [ ! -f "$1" ] || [ ! -r "$1" ]
then
    echo -e "\nUsage: $ spellcheck {readable file}\n"
    exit 1
fi

additionalWords="/dev/null"
declare -r aw="$HOME/.aspell.en.pws"
[ -f "$aw" ] && [ -r "$aw" ] && additionalWords="$aw"

cat "$1" | \
    tr '[:blank:][:cntrl:][:punct:][:space:][:digit:]' '\n' | \
    aspell --ignore-case --dont-suggest -p "$additionalWords" list | \
    sed -r 's/^@\(#\) .*+//' | \
    tr '[:blank:][:cntrl:][:punct:][:space:][:digit:]' '\n' | \
    sort -u

