#!/bin/bash


# Runs a passed in command (line) under a randomly named temporary user.
#
# Deletes the temp user after the passed in command exits.
#
# Passed in command's start dir is temp user's home dir.
#
# Files created in the temp user's home dir that should be retained after this
# script exits need to be copied or moved from the temp user's home dir before
# exiting the passed in command.


# Copyright (C) 2018,2020 drpawpaw. All Rights Reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ 0 != "$(id -u)" ]
then
    echo -e "\n${0##*/} only runs as root." >&2
    exit 1
fi


for e in grep id sudo tmp-user
do
    if ! which $e &>/dev/null
    then
        echo -e "\n${0##*/} needs ${e}. Didn't find it.\n" >&2
        exit 1
    fi
done


if [ -z "$1" ]
then
    echo -e "\n${0##*/}: No command passed in to run under a temp user.\n" >&2
    exit 1
fi


if echo $* | grep -E '^sudo ' &>/dev/null
then
    echo -e "\nThis script's tmp users can't run sudo root executables." \
            "Use tmp-user to build a script than can." >&2
    exit
fi


userName=$( tmp-user -c )
if [ -z "$userName" ] || ! id $userName &>/dev/null
then
    echo -e "\nFailed to create a tmp user." >&2
    exit 1
fi

echo >&2
sudo --login -u $userName $@

tmp-user -d $userName

